server/server/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('usman.urls')),
    path('admin/', admin.site.urls),
]

server/usman/urls.py
from django.urls import path
from . import views

app_name = 'usman'

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:zone_name>', views.control, name='control')
]

server/usman/models.py
from django.db import models

# Create your models here.
class Zone(models.Model):
    zone_name = models.CharField(max_length=5)
    description = models.CharField(max_length=11, default="N/A")
    floor = models.IntegerField(default=1)
    temperature_set = models.IntegerField(default=20)
    temperature_actual = models.DecimalField(decimal_places=1, max_digits=2, default=0.0)
    light_color = models.CharField(max_length=6, default='00FF00')

    def __str__(self):
        return self.zone_name

server/usman/views.py
from django.http import HttpResponse
from django.template import loader
from .models import Zone

# Create your views here.
def index(request):
    context = {
        'first_floor_zones': Zone.objects.filter(floor=1),
        'second_floor_zones': Zone.objects.filter(floor=2)
    }
    template = loader.get_template('usman/index.html')
    return HttpResponse(template.render(context, request))

def control(request, zone_name):
    zone_selected = Zone.objects.get(zone_name=zone_name)

    if request.method == 'POST':
        print(request.POST)
        if 'temp_set' in request.POST:
            temp_set = int(request.POST['temp_set'])
            if 15 <= temp_set <= 30:
                zone_selected.temperature_set = temp_set
                zone_selected.save()
        if 'color_set' in request.POST:
            zone_selected.light_color = request.POST['color_set']
            zone_selected.save()
    context = {
        'zone_selected': zone_selected
    }
    template = loader.get_template('usman/control.html')
    return HttpResponse(template.render(context, request))

server/usman/templates/usman/control.html
<html>
    <head>
        <title>Usman Smart Home</title>
    </head>
    <body>
        <h2>FLOOR {{ zone_selected.floor }} - {{ zone_selected.description }} CONTROLS</h2>
    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}
        <p>Actual temperature: {{ zone_selected.temperature_actual }}</p>
        <form action="{% url 'usman:control' zone_selected.zone_name %}" method="POST">
            {% csrf_token %}
            <label for="temp_set">Set temperature: {{ zone_selected.temperature_set }}</label><br><br>
            <input type="range" name="temp_set" id="temp_set" min="15" max="30" value="{{ zone_selected.temperature_set }}">
            <input type="submit" value="Set Temperature">
        </form>
        <br>
        <form action="{% url 'usman:control' zone_selected.zone_name %}" method="POST">
            {% csrf_token %}
            <label for="color_set">Light Color: {{ zone_selected.light_color }}</label><br>
            <input type="text" name="color_set" id="color_set" value="{{ zone_selected.color_set }}">
            <input type="submit" value="Set Color">
        </form>
    </body>
</html>

server/usman/templates/usman/index.html
<html>
    <head>
        <title>Usman Smart Home</title>
    </head>
    <body>
    {% if first_floor_zones %}
        <h3>First Floor Zones</h3>
        <ul>
        {% for zone in first_floor_zones %}
            <li><a href="/{{ zone.zone_name }}">{{ zone.description }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No zones found for first floor in the database!</p>
    {% endif %}

    {% if second_floor_zones %}
        <h3>Second Floor Zones</h3>
        <ul>
        {% for zone in second_floor_zones %}
            <li><a href="/{{ zone.zone_name }}">{{ zone.description }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No zones found for second floor in the database!</p>
    {% endif %}
    </body>
</html>